#pragma once

#define IDR_BRAINROT_TRALALERO 101
#define IDR_BRAINROT_BALLERINA 102
#define IDR_BRAINROT_BOMBARDIRO 103
#define IDR_CAT_SHOCKED 104
#define IDR_CAT_JUDGMENTAL 105
#define IDR_CAT_VACANT 106
#define IDR_CAT_SUSPICIOUS 107

