#pragma once

#define IDR_BRAINROT_TRALALERO 101
#define IDR_BRAINROT_BALLERINA 102
#define IDR_BRAINROT_BOMBARDIRO 103
#define IDR_CAT_SHOCKED 104
#define IDR_CAT_JUDGMENTAL 105
#define IDR_CAT_VACANT 106
#define IDR_CAT_SUSPICIOUS 107
#define IDR_USER_GOOSE_ICE_CREAM 108
#define IDR_USER_GOOSE_WORKER 109
#define IDR_USER_GOOSE_CALL 110
#define IDR_USER_GOOSE_STORE 111
#define IDR_USER_GOOSE_PUNCHY 112
#define IDR_USER_GOOSE_GANGSTER 113
#define IDR_USER_GOOSE_JET 114
